# Generated by Django 4.2.3 on 2023-09-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('prod_ref', models.IntegerField(default=100)),
                ('item_name', models.CharField(max_length=200)),
                ('op_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='for_user',
            field=models.CharField(default='Alex', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='prod_code',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis quasi magni, consequuntur aliquam eveniet, nihil temporibus nam voluptatem, eaque fugit illum id adipisci sapiente repellat delectus? Eius nostrum debitis officia!', max_length=300),
        ),
    ]
